"""Business logic services for AITEA.

This module provides service interfaces and implementations for:
- Feature library management
- Time tracking
- Project estimation
- JSON persistence
- LLM provider abstraction
"""

from .interfaces import (
    IFeatureLibraryService,
    ITimeTrackingService,
    IEstimationService,
    ImportResult,
)
from .implementations import (
    FeatureLibraryService,
    TimeTrackingService,
    EstimationService,
)
from .persistence import (
    FeatureLibraryPersistence,
    TimeTrackingPersistence,
)
from .csv_import import (
    import_csv_file,
    validate_row,
    REQUIRED_COLUMNS,
)
from .llm import (
    LLMProvider,
    MockLLM,
    ChatMessage,
    get_llm_provider,
    MOCK_MODE_WARNING,
)
from .providers import (
    OpenAIProvider,
    AnthropicProvider,
    BedrockProvider,
    ProviderConfig,
)
from .prompts import (
    PromptTemplate,
    ChatPromptTemplate,
    MessageTemplate,
    Example,
    PromptTemplateError,
    MissingVariableError,
    create_cot_prompt,
    create_few_shot_prompt,
    get_template,
    list_templates,
    TEMPLATES,
    FEATURE_EXTRACTION_TEMPLATE,
    ESTIMATION_TEMPLATE,
    PROJECT_ESTIMATION_TEMPLATE,
    BRD_PARSING_TEMPLATE,
)
from .output_parsers import (
    OutputParser,
    OutputParserError,
    JsonParseError,
    ValidationParseError,
    JsonOutputParser,
    ListOutputParser,
    ExtractedFeature,
    FeatureExtractionResponse,
    EstimationResponse,
    ProjectEstimationResponse,
    BRDFeature,
    BRDParseResponse,
    feature_extraction_parser,
    estimation_parser,
    project_estimation_parser,
    brd_parser,
    feature_list_parser,
    get_parser,
    list_parsers,
)
from .tools import (
    ToolParameter,
    ToolDefinition,
    ToolRegistry,
    JsonSchemaValidationError,
    JsonSchemaValidator,
    validate_json_schema,
    add_feature_tool,
    search_features_tool,
    list_features_tool,
    get_feature_tool,
    estimate_feature_tool,
    estimate_project_tool,
    add_time_entry_tool,
    get_feature_statistics_tool,
    import_time_csv_tool,
    get_default_tool_registry,
    AITEA_TOOLS,
)
from .streaming import (
    StreamChunk,
    StreamingResponse,
    StreamCallback,
    BaseStreamCallback,
    PrintStreamCallback,
    CollectorStreamCallback,
    BufferedStreamCallback,
    ThrottledStreamCallback,
    stream_response,
    stream_with_callback,
    stream_chat_with_callback,
    collect_stream,
    stream_to_string,
)
from .tokens import (
    ModelFamily,
    TruncationStrategy,
    MODEL_CONTEXT_WINDOWS,
    MODEL_PRICING,
    TokenCounter,
    OpenAITokenCounter,
    AnthropicTokenCounter,
    BedrockTokenCounter,
    MockTokenCounter,
    get_token_counter,
    get_context_window,
    estimate_cost,
    ContextWindowManager,
    TokenUsage,
    TokenBudget,
    TokenBudgetExceededError,
)

__all__ = [
    # Service interfaces
    "IFeatureLibraryService",
    "ITimeTrackingService",
    "IEstimationService",
    # Service implementations
    "FeatureLibraryService",
    "TimeTrackingService",
    "EstimationService",
    # Persistence services
    "FeatureLibraryPersistence",
    "TimeTrackingPersistence",
    # CSV import
    "import_csv_file",
    "validate_row",
    "REQUIRED_COLUMNS",
    # LLM providers
    "LLMProvider",
    "MockLLM",
    "ChatMessage",
    "get_llm_provider",
    "MOCK_MODE_WARNING",
    # Multi-provider implementations
    "OpenAIProvider",
    "AnthropicProvider",
    "BedrockProvider",
    "ProviderConfig",
    # Prompt templates
    "PromptTemplate",
    "ChatPromptTemplate",
    "MessageTemplate",
    "Example",
    "PromptTemplateError",
    "MissingVariableError",
    "create_cot_prompt",
    "create_few_shot_prompt",
    "get_template",
    "list_templates",
    "TEMPLATES",
    "FEATURE_EXTRACTION_TEMPLATE",
    "ESTIMATION_TEMPLATE",
    "PROJECT_ESTIMATION_TEMPLATE",
    "BRD_PARSING_TEMPLATE",
    # Output parsers
    "OutputParser",
    "OutputParserError",
    "JsonParseError",
    "ValidationParseError",
    "JsonOutputParser",
    "ListOutputParser",
    "ExtractedFeature",
    "FeatureExtractionResponse",
    "EstimationResponse",
    "ProjectEstimationResponse",
    "BRDFeature",
    "BRDParseResponse",
    "feature_extraction_parser",
    "estimation_parser",
    "project_estimation_parser",
    "brd_parser",
    "feature_list_parser",
    "get_parser",
    "list_parsers",
    # Tool definitions
    "ToolParameter",
    "ToolDefinition",
    "ToolRegistry",
    "JsonSchemaValidationError",
    "JsonSchemaValidator",
    "validate_json_schema",
    "add_feature_tool",
    "search_features_tool",
    "list_features_tool",
    "get_feature_tool",
    "estimate_feature_tool",
    "estimate_project_tool",
    "add_time_entry_tool",
    "get_feature_statistics_tool",
    "import_time_csv_tool",
    "get_default_tool_registry",
    "AITEA_TOOLS",
    # Streaming
    "StreamChunk",
    "StreamingResponse",
    "StreamCallback",
    "BaseStreamCallback",
    "PrintStreamCallback",
    "CollectorStreamCallback",
    "BufferedStreamCallback",
    "ThrottledStreamCallback",
    "stream_response",
    "stream_with_callback",
    "stream_chat_with_callback",
    "collect_stream",
    "stream_to_string",
    # Data types
    "ImportResult",
    # Token management
    "ModelFamily",
    "TruncationStrategy",
    "MODEL_CONTEXT_WINDOWS",
    "MODEL_PRICING",
    "TokenCounter",
    "OpenAITokenCounter",
    "AnthropicTokenCounter",
    "BedrockTokenCounter",
    "MockTokenCounter",
    "get_token_counter",
    "get_context_window",
    "estimate_cost",
    "ContextWindowManager",
    "TokenUsage",
    "TokenBudget",
    "TokenBudgetExceededError",
]
